# Site settings
title: "Ogunseye Olatunde David"
description: " Propective data scientist, passionate at solving complex problems across multiple industries such as Engineering, Finance Sales through innovative approaches etc."
logo: Asset/06c3649c-864f-460c-934c-8f4ebb14202e.jpeg
show_downloads: true
url: "https://yourusername.github.io" # The URL of your site
email: ogunseyeolatunde2@gmail.com
linkedin: (https//www.linkedin.com/in/ogunseye-olatunde-david)
theme: jekyll-theme-minimal
