# Site settings
title: "Ogunseye Olatunde David"
description: "Welcome to my space,  "
baseurl: "" # The subpath of your site, e.g. /blog if your site is at example.github.io/blog
url: "https://yourusername.github.io" # The URL of your site

# Markdown settings
markdown: kramdown
highlighter: rouge

# Theme settings
theme: jekkyll-theme-minima # You can replace 'minima' with the name of another theme

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Social media links (optional)
twitter_username: your_twitter_username
github_username: your_github_username

# Pagination settings
paginate: 5 # Number of posts per page

# Exclude these from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Include additional files
include:
  - _pages

# Permalink structure
permalink: /:categories/:title/
